### ISSUE TITLE
Cleanup tmp bam files If map_reads rule fails

### ISSUE THREAD

**Issue by SGMartin** [cnio-bu/varca#2]
This is a suggestion/enhancement, but I personally find quite annoying that, when the rule map_reads fails for whatever reason (i.e. insufficient mem), the temporary bam files (sample_.bam.tmp) are not automatically removed. This causes issues down the line because bwa will try to generate the same temporary files again and again and the rule will keep crashing due to these files being already present, even If the original issue is fixed.

**Comment by tdido** [comment]
Maybe `shadow:"shallow"` like in the indexing step?

**Comment by SGMartin** [comment]
That might do the trick! If I have any spare time today I'll make a PR.

Quoting snakemake docs for docs purposes.
```
This is useful for running programs that generate lots of unused files which you don’t want to manually cleanup in your snakemake workflow. It can also be useful if you want to keep your workdir clean while the program executes, or simplify your workflow by not having to worry about unique filenames for all outputs of all rules.

By setting shadow: "shallow", the top level files and directories are symlinked, so that any relative paths in a subdirectory will be real paths in the filesystem. 
```
